# Generated by Django 5.2.4 on 2025-08-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='copright',
            new_name='copyright',
        ),
    ]
