# Generated by Django 5.2.4 on 2025-08-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_copright_blog_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='copyright',
            field=models.TextField(max_length=500),
        ),
    ]
